scalar JSON
scalar DateTime

type Profile{
    name:        String!
    description: String!
    githubUrl:   String!
    linkedinUrl: String
    otherLinks:  JSON
    projects:       [Project!]!
    skills:         [Skill!]!
    workExperience: [WorkExperience!]!
}

type Project{
    name:        String!
    description: String!
    sourceUrl:   String!
    demoUrl:     String
}

type Skill{
    name:      String!
    category:  String!
}

type WorkExperience{
    company:      String!
    position:     String!
    startDate:    DateTime!
    endDate:      DateTime!
    achievements: String!
}

type Query{
    profile: Profile!
    skills: [Skill!]!
    experience: [WorkExperience!]!
    projects: [Project!]!
}